version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_app
    env_file:
      - .env
    ports:
      - "8282:8081"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8181:80"
    restart: always

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always
